server:
  port: 8083

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: kickstarter
  datasource:
    url: "jdbc:h2:file:./database/database-shopping-cart;AUTO_SERVER=TRUE"
    username: "celfoucs"
    password: "change-me"
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/shopping-cart
          principal-claim-name: preferred_username
          authority-prefix: ROLE_
          authorities-claim-name: roles

otel:
  instrumentation:
    logback-appender:
      experimental:
        capture-logger-context-attributes: true
  logs:
    exporter: otlp
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://grafana:4318
